name: scgen
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.12
    - pip
    - pip:
        - scanpy
        - scvi-tools
        - pertpy
        - scgen[tutorials]
        - jupyter
#prefix: /path/to/envs/scgen
#please edit the above line to your conda installation
