name: sc-analysis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - scanpy
  - anndata
  - pertpy
  - scvi-tools
  - pytorch
  - pytorch-lightning
  - scikit-learn
  - matplotlib
  - seaborn
  - pip
  - pip:
      - torchmetrics
