name: scgen
channels:
  - conda-forge          
  - bioconda             
dependencies:
  - python=3.11
  - scanpy
  - scvi-tools
  - optuna    
  - pertpy            
  - jupyterlab           
  - ipywidgets           
  - pip