name: scgen
channels:
  - conda-forge          
  - bioconda             
dependencies:
  - python=3.11
  - scanpy
  - scvi-tools
  - optuna
  - scipy<1.16              
  - jupyterlab           
  - ipywidgets           
  - pip
  - pip:
      - scikit-misc
      - pertpy