name: scgen
channels:
  - conda-forge          
  - bioconda             
dependencies:
  - python=3.10
  - scanpy
  - scvi-tools
  - pertpy
  - optuna               
  - jupyterlab           
  - ipywidgets           
  - pip
  - pip:
      - scgen