name: scgen
channels:
  - conda-forge          
  - bioconda             
dependencies:
  - python=3.11
  - scanpy=1.9.3
  - anndata=0.10.8 
  - scvi-tools=0.14.6
  - optuna
  - scipy<1.16
  - pytorch-lightning=1.3.8
  - torchmetrics<0.8              
  - jupyterlab           
  - ipywidgets           
  - pip
  - pip:
      - scikit-misc
      - pertpy==1.0.0 
      - "jax[cpu]==0.6.2"
      - numpyro==0.18.0
      - setuptools<=59.5 