name: scgen
channels:
  - pytorch
  - conda-forge          
  - bioconda             
dependencies:
  - python=3.11
  - pytorch==2.2.*
  - pytorch-cuda=11.8
  - torchvision
  - torchaudio
  - scanpy
  - scvi-tools
  - pertpy
  - optuna               
  - jupyterlab           
  - ipywidgets           
  - pip