name: scgen
channels:
  - conda-forge          
  - bioconda             
dependencies:
  - python=3.11
  - scanpy
  - scvi-tools
  - optuna               
  - jupyterlab           
  - ipywidgets           
  - pip
  - pip:
      - scgen==2.1.0
      - pertpy==1.0.0
      - scikit-misc==0.5.1