name: scpram
channels:
  - pytorch
  - conda-forge
  - bioconda
dependencies:
  - python=3.8
  - pytorch==2.2.*
  - pytorch-cuda=11.8
  - torchvision
  - torchaudio
  - scanpy
  - optuna
  - jupyterlab      
  - ipywidgets  
  - pip
  - pip:
      - scpram